name: Manually triggered deploy to Open Source Cloud Development Environment

on: workflow_dispatch

jobs:
  dispatch-osaas-dev-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch development fork deploy workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          repository: eyevinn-osaas-dev/intercom-manager
          event-type: deploy
